# Generated by Django 6.0.2 on 2026-04-30 15:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='student_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_supervisor_department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_supervisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_supervisor_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='internshipplacement',
            name='workplace_supervisor_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='friday_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='monday_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='thursday_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='tuesday_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklylog',
            name='wednesday_activities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='activities',
            field=models.TextField(blank=True),
        ),
    ]
