# Generated by Django 6.0.2 on 2026-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_feedback_score_internshipplacement_student_notes_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.UniqueConstraint(fields=('weekly_log', 'supervisor'), name='unique_feedback_per_supervisor_per_weekly_log'),
        ),
    ]
